language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./waf configure && ./waf build_debug && ./waf build_dev && ./waf build_release && cd test/ && ../waf configure && ../waf build && build/gainputtest && cd ..
